parameters:
  monsieurbiz.search.model.documentable.interface: MonsieurBiz\SyliusSearchPlugin\Model\Documentable\DocumentableInterface
  monsieurbiz.search.request.interface: MonsieurBiz\SyliusSearchPlugin\Search\Request\RequestInterface

services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      Sylius\Bundle\ResourceBundle\Controller\ParametersParserInterface: '@sylius.resource_controller.parameters_parser'
      $localeProvider: '@sylius.translation_locale_provider'
      $productVariantResolver: '@sylius.product_variant_resolver.default'
      $documentableRegistry: '@monsieurbiz.search.registry.documentable'
      $searchRequestsRegistry: '@monsieurbiz.search.registry.search_request'

  MonsieurBiz\SyliusSearchPlugin\:
    resource: '../../*'
    exclude: '../../{Entity,Migrations,Tests,Kernel.php}'

  MonsieurBiz\SyliusSearchPlugin\Form\Extension\:
    resource: '../../Form/Extension'
    tags:
      - { name: form.type_extension }

  MonsieurBiz\SyliusSearchPlugin\Generated\:
    resource: '../../../generated'

  # ES Client configuration
  MonsieurBiz\SyliusSearchPlugin\Search\ClientFactory:
    arguments:
      $config:
        host: '%env(MONSIEURBIZ_SEARCHPLUGIN_ES_HOST)%'
        port: '%env(MONSIEURBIZ_SEARCHPLUGIN_ES_PORT)%'

  MonsieurBiz\SyliusSearchPlugin\Repository\ProductAttributeRepository:
    arguments:
      $attributeRepository: '@sylius.repository.product_attribute'

  # Define our mapping provider
  JoliCode\Elastically\Mapping\YamlProvider:
    arguments:
      $configurationDirectory: '@=service("file_locator").locate("@MonsieurBizSyliusSearchPlugin/Resources/config/elasticsearch")'
  MonsieurBiz\SyliusSearchPlugin\Mapping\YamlWithLocaleProvider:
    decorates: JoliCode\Elastically\Mapping\YamlProvider
    arguments:
      $decorated: '@.inner'

  # Defines our registries
  monsieurbiz.search.registry.documentable:
    class: Sylius\Component\Registry\ServiceRegistry
    arguments:
      $className: '%monsieurbiz.search.model.documentable.interface%'
      $context: 'documentable'

  monsieurbiz.search.registry.search_request:
    class: Sylius\Component\Registry\ServiceRegistry
    arguments:
      $className: '%monsieurbiz.search.request.interface%'
      $context: 'documentable'

  # Define product attribute value readers
  MonsieurBiz\SyliusSearchPlugin\AutoMapper\ProductAttributeValueConfiguration:
    arguments:
      $productAttributeValueReaders: {
        default: '@MonsieurBiz\SyliusSearchPlugin\AutoMapper\ProductAttributeValueReader\DefaultReader',
        select: '@MonsieurBiz\SyliusSearchPlugin\AutoMapper\ProductAttributeValueReader\SelectReader',
        date: '@MonsieurBiz\SyliusSearchPlugin\AutoMapper\ProductAttributeValueReader\DateReader'
      }

  # Define aggregation builders
  MonsieurBiz\SyliusSearchPlugin\Search\Request\Aggregation\MainTaxonAggregation:
    tags: { name: 'monsieurbiz.sarch.aggregation_builder' }

  MonsieurBiz\SyliusSearchPlugin\Search\Request\Aggregation\TaxonsAggregation:
    tags: { name: 'monsieurbiz.sarch.aggregation_builder' }

  MonsieurBiz\SyliusSearchPlugin\Search\Request\Aggregation\PriceAggregation:
    tags: { name: 'monsieurbiz.sarch.aggregation_builder' }

  MonsieurBiz\SyliusSearchPlugin\Search\Request\Aggregation\ProductAttributesAggregation:
    tags: { name: 'monsieurbiz.sarch.aggregation_builder' }

  MonsieurBiz\SyliusSearchPlugin\Search\Request\Aggregation\ProductOptionsAggregation:
    tags: { name: 'monsieurbiz.sarch.aggregation_builder' }

  MonsieurBiz\SyliusSearchPlugin\Search\Request\AggregationBuilder:
    arguments: [ !tagged_iterator { tag: 'monsieurbiz.sarch.aggregation_builder' } ]

  # Define query filters
  MonsieurBiz\SyliusSearchPlugin\Search\Request\QueryFilter\ProductSearchRegistry:
    arguments:
      - [
          '@MonsieurBiz\SyliusSearchPlugin\Search\Request\QueryFilter\Product\SearchTermFilter',
          '@MonsieurBiz\SyliusSearchPlugin\Search\Request\QueryFilter\Product\ChannelFilter',
          '@MonsieurBiz\SyliusSearchPlugin\Search\Request\QueryFilter\Product\EnabledFilter'
      ]

  MonsieurBiz\SyliusSearchPlugin\Search\Request\QueryFilter\ProductTaxonRegistry:
    arguments:
      - [
          '@MonsieurBiz\SyliusSearchPlugin\Search\Request\QueryFilter\Product\ChannelFilter',
          '@MonsieurBiz\SyliusSearchPlugin\Search\Request\QueryFilter\Product\EnabledFilter',
          '@MonsieurBiz\SyliusSearchPlugin\Search\Request\QueryFilter\Product\TaxonFilter'
      ]

  # Define post filters
  MonsieurBiz\SyliusSearchPlugin\Search\Request\PostFilter\ProductTaxonRegistry:
    arguments:
      - [
        '@MonsieurBiz\SyliusSearchPlugin\Search\Request\PostFilter\Product\AttributesPostFilter',
        '@MonsieurBiz\SyliusSearchPlugin\Search\Request\PostFilter\Product\MainTaxonPostFilter',
        '@MonsieurBiz\SyliusSearchPlugin\Search\Request\PostFilter\Product\OptionsPostFilter',
        '@MonsieurBiz\SyliusSearchPlugin\Search\Request\PostFilter\Product\PricePostFilter',
        '@MonsieurBiz\SyliusSearchPlugin\Search\Request\PostFilter\Product\ProductTaxonPostFilter',
      ]

  # Define sorters
  MonsieurBiz\SyliusSearchPlugin\Search\Request\Sorting\ProductSorterRegistry:
    arguments:
      - [
        '@MonsieurBiz\SyliusSearchPlugin\Search\Request\Sorting\Product\PositionSorter',
        '@MonsieurBiz\SyliusSearchPlugin\Search\Request\Sorting\Product\PriceSorter',
        '@MonsieurBiz\SyliusSearchPlugin\Search\Request\Sorting\Product\NameSorter',
        '@MonsieurBiz\SyliusSearchPlugin\Search\Request\Sorting\Product\CreatedAtSorter',
      ]

  # Define the product queries
  MonsieurBiz\SyliusSearchPlugin\Search\Request\ProductRequest\Search:
    arguments:
      $queryFilterRegistry: '@MonsieurBiz\SyliusSearchPlugin\Search\Request\QueryFilter\ProductSearchRegistry'
      $postFilterRegistry: '@MonsieurBiz\SyliusSearchPlugin\Search\Request\PostFilter\ProductTaxonRegistry'
      $sorterRegistry: '@MonsieurBiz\SyliusSearchPlugin\Search\Request\Sorting\ProductSorterRegistry'

  MonsieurBiz\SyliusSearchPlugin\Search\Request\ProductRequest\InstantSearch:
    arguments:
      $queryFilterRegistry: '@MonsieurBiz\SyliusSearchPlugin\Search\Request\QueryFilter\ProductSearchRegistry'

  MonsieurBiz\SyliusSearchPlugin\Search\Request\ProductRequest\Taxon:
    arguments:
      $queryFilterRegistry: '@MonsieurBiz\SyliusSearchPlugin\Search\Request\QueryFilter\ProductTaxonRegistry'
      $postFilterRegistry: '@MonsieurBiz\SyliusSearchPlugin\Search\Request\PostFilter\ProductTaxonRegistry'
      $sorterRegistry: '@MonsieurBiz\SyliusSearchPlugin\Search\Request\Sorting\ProductSorterRegistry'

  # Define the filter builders
  MonsieurBiz\SyliusSearchPlugin\Search\ResponseFactory:
    arguments:
      $filterBuilders: {
        product_main_taxon: '@MonsieurBiz\SyliusSearchPlugin\Search\Response\FilterBuilders\Product\MainTaxonFilterBuilder',
        product_taxons: '@MonsieurBiz\SyliusSearchPlugin\Search\Response\FilterBuilders\Product\TaxonsFilterBuilder',
        product_price: '@MonsieurBiz\SyliusSearchPlugin\Search\Response\FilterBuilders\Product\PriceFilterBuilder',
        product_attribute: '@MonsieurBiz\SyliusSearchPlugin\Search\Response\FilterBuilders\Product\AttributeFilterBuilder'
      }
