name: Flex Recipe

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  recipe:

    runs-on: ubuntu-latest

    env:
      SYMFONY_ENDPOINT: http://127.0.0.1/

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']
        sylius: ["~1.12.0"]

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: date.timezone=UTC

      - name: Set project php-version
        run: |
          echo "${{ matrix.php }}" > .php-version

      - uses: actions/checkout@v2
        with:
          path: plugin

      # Run the server at the start so it can download the recipes!
      - name: Run standalone symfony flex server
        run: |
          echo ${{ github.token }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker run --rm --name flex -d -v $PWD/plugin/recipes:/var/www/flex/var/repo/private/monsieurbiz/sylius-search-plugin -p 80:80 docker.pkg.github.com/monsieurbiz/docker/symfony-flex-server:latest contrib official
          docker ps

      - run: mkdir -p /home/runner/{.composer/cache,.config/composer}

      - uses: actions/cache@v1
        id: cache-composer
        with:
          path: /home/runner/.composer/cache
          key: composer2-php:${{ matrix.php }}-sylius:${{ matrix.sylius }}-${{ github.sha }}
          restore-keys: composer2-php:${{ matrix.php }}-sylius:${{ matrix.sylius }}-

      - name: Update composer
        run: sudo composer self-update

      - name: Composer Github Auth
        run: composer config -g github-oauth.github.com ${{ github.token }}

      - name: Create Sylius-Standard project without install
        run: |
          composer create-project --prefer-dist --no-scripts --no-progress --no-install sylius/sylius-standard sylius "${{ matrix.sylius }}"

      # Because the sylius-standard has a soft constraint
      - name: Make sure to install the required version of Sylius
        working-directory: ./sylius
        run: |
            composer require --no-install --no-scripts --no-progress sylius/sylius="${{ matrix.sylius }}"

        # Fix Paypal 1.5 on Sylius 1.12 and PHP 8.1
      - name: Make sure to install the required version of Sylius Paypal Plugin
        if: ${{ matrix.sylius_paypal }}
        working-directory: ./sylius
        run: |
            composer require --no-install --no-scripts --no-progress sylius/paypal-plugin="${{ matrix.sylius_paypal }}" # @see https://github.com/Sylius/PayPalPlugin/issues/295


      - name: Setup some requirements
        working-directory: ./sylius
        run: |
            composer config --no-plugins allow-plugins true
            composer config --no-plugins extra.symfony.allow-contrib true
            composer config --no-plugins secure-http false
            composer config --no-plugins --unset platform.php
            composer config --no-plugins extra.symfony.docker false
            composer config --no-plugins --json extra.symfony.endpoint '["https://api.github.com/repos/monsieurbiz/symfony-recipes/contents/index.json?ref=flex/master","flex://defaults"]'
            composer config repositories.plugin '{"type": "path", "url": "../plugin/"}'

      - name: Require plugin without install
        working-directory: ./sylius
        run: |
          composer require --no-install --no-scripts monsieurbiz/sylius-search-plugin="*@dev"

      - name: Composer install
        working-directory: ./sylius
        run: |
          composer install

      - name: Show flex server logs
        run: docker logs --tail 100 flex
